<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <h1>New Car</h1>

        <div>
            <a href="/cars">cars list</a>
        </div>
        <br>
        <form class="form" action="/cars" method="post">
            <div>
                <b>Model</b>
                <input type="text" name="car[model]" value="<?= $car['model'] ?>">
                <?php if (isset($errors['model'])) : ?>
                    <div style="color: red"><?= $errors['model']?></div>
                <?php endif ?>
                <br>
                <br>
                Year
                <input type="text" name="car[year]" value="<?= $car['year'] ?>">
            </div><br>
            <div><input type="submit"></div>
        </form>
    </body>
</html>
