<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title></title>
  </head>
  <body>
    <h1>New Car</h1>
    <div><a href="/cars">cars list</a></div>
    <br>
    <form enctype="multipart/form-data" action="/cars" method="post">
      <div>
        <b>Model</b>
        <input type="text" name="car[model]" value"<?= $car['model'] ?>">
        <?php if (isset($errors['model'])) : ?>
          <div style="color: red"><?= $errors['model'] ?></div>
        <?php endif ?>
      </div>
      <br>
      <div>
        Picture <br><br>
        <?php if (isset($errors['pictures'])) : ?>
          <div style="color: red"><?= $errors['pictures'] ?></div>
        <?php endif ?>
        <input class="file" type="file" name="car[pictures][]"><br>
        <input class="file" type="file" name="car[pictures][]">
      </div><br>
      <div><input type="submit"></div>
    </form>

  </body>
</html>
